Dropdown-component
Datacom-Endeavour-Design-System/endeavour pull request #140
Opened 2024-02-15 07:21 UTC by sidra2022

This pull request contains the following modifications to achieve the designer's feedback.
- Add the animation for **SVG(Chevron**) and remove the **Chevron SVG** duplication for this purpose in the component.
- Add stories based on the feedback.

2024-02-15 22:21 UTC, 4leite requested changes

2024-02-15 22:21 UTC, 4leite commented on apps/storybook/src/components/stable/datacom-dropdown.stories.tsx
> +import { HTMLDatacomDropdownElement } from 'packages/stencil/dist/types/components/datacom-dropdown/datacom-dropdown';
remove this line to resolve type conflict

2024-02-25 20:48 UTC, louislingatong approved these changes
please merge to lates and resolve conflicts. thanks

2024-02-26 21:37 UTC, 4leite approved these changes
nice one

2024-02-26 21:47 UTC, merged