Time picker component
Datacom-Endeavour-Design-System/endeavour pull request #157
Opened 2024-04-23 15:37 UTC by louislingatong

2024-04-30 23:17 UTC, sidra2022 requested changes

2024-05-01 00:49 UTC, louislingatong commented on packages/stencil/src/components/datacom-time-picker/usage.md
> +    <DatacomTimePicker
Done

2024-05-01 00:49 UTC, louislingatong commented on packages/stencil/src/global/global.css
> +  --dc-date-time-picker-disabled-color: var(--dc-token-disabled-02);
Done

2024-05-01 00:49 UTC, louislingatong commented on packages/stencil/src/global/global.css
> +  --dc-date-time-picker-primary-interactive-color: var(--dc-token-interactive-01);
Done

2024-05-01 00:49 UTC, louislingatong commented on packages/stencil/src/global/global.css
> +  --dc-date-time-picker-text-icon-color: var(--dc-token-text-05);
Done

2024-05-01 00:52 UTC, louislingatong commented on packages/stencil/src/components/datacom-time-picker/datacom-time-picker.tsx
> +      // 00: - 23:
Enhance inline comment for better understanding.

I believe using a block comment "/** */" is good for function/method documentation while inline comment "// " is good for inline code logic.

2024-05-01 02:56 UTC, sidra2022 approved these changes

2024-05-01 03:56 UTC, merged