Link component is added.
Datacom-Endeavour-Design-System/endeavour pull request #61
Opened 2023-03-13 23:16 UTC by sidra2022

2023-03-29 01:13 UTC, AngeCast requested changes
Hey there. Got some comments. Have a look when you can.

2023-03-29 01:13 UTC, AngeCast commented on packages/stencil/src/components/datacom-link/datacom-link.css
A lot of your CSS selectors are quite long and I imagine could be shortened and simplified.

For example you prefix a lot of these rules with '.dc-link', when the subsequent class is already on the same element.

Another egregious example is something like:
`.dc-link.dc-link-footer:hover:not(.dc-link-disabled)`

I feel like all this needed to be was:
`.dc-link-footer:hover`

And any disabled styles should be handled by classes further down the file.

MIght be worth going back through all your CSS selectors and seeing if you can simplify them. This'll help with readability and easier maintainability for the future.

Happy to do this along with you if you need the help as well.

2023-03-29 01:13 UTC, AngeCast commented on packages/stencil/src/components/datacom-link/datacom-link.tsx
> +        <div class="dc-link-wrapper">
Same thing as the 'dc-link-image-' class comment previously. I feel like you don't need so many nested elements like this. 

Honestly, the CSS for the dc-link-wrapper should just be part of the .dc-link CSS class.

Try to keep the HTML like your CSS as simple as possible.

2023-03-30 02:01 UTC, AngeCast requested changes
Still got comments. Might be worth re-thinking how you approach the different variants.

2023-03-30 02:01 UTC, AngeCast commented on packages/stencil/src/components/datacom-link/datacom-link.css
> +  border-bottom: var(--link-visited-color);
This should just be border-color. (But perhaps this might not matter, considering my previous comment about removing borders entirely.)

2023-04-01 03:15 UTC, sidra2022 commented on packages/stencil/src/components/datacom-link/datacom-link.css
> +.dc-link:hover:not(:focus-visible)::before {
Do not need animation for focus state.

2023-04-01 03:15 UTC, sidra2022 commented on packages/stencil/src/components/datacom-link/datacom-link.tsx
> +        <a class={Classes} href={this.url}>
Fixed

2023-04-01 03:16 UTC, sidra2022 commented on packages/stencil/src/components/datacom-link/datacom-link.css
> +.dc-link.dc-link-disabled {
Fixed

2023-04-03 23:02 UTC, AngeCast requested changes
I think the CSS is almost there. Just a couple more comments from me.

2023-04-03 23:02 UTC, AngeCast commented on packages/stencil/src/components/datacom-link/datacom-link.css
Nice one, I think most of the selectors look good now. Next step might be looking into seeing if you can organize and group the rules by their classes. Because right now, if I need to look at the styles for the .dc-link-inline class for example, all related rules are all over the place on this file. 

It would be good to move them all side by side if possible. (And in the case that a rule needs to be in the position it is in the file, you could add a comment to explain why.)

If you need examples of how to organize, look at the accordion or button CSS files. They seem like decent examples.

2023-04-04 01:19 UTC, sidra2022 commented on packages/stencil/src/components/datacom-link/datacom-link.css
> +}
Fixed

2023-04-04 01:38 UTC, sidra2022 commented on packages/stencil/src/components/datacom-link/datacom-link.css
I have organized the CSS file properly and kept selectors in that order to render correctly. In addition, I also added some comments. Please Re-review when you can. Thanks for your support.

2023-04-04 01:42 UTC, AngeCast requested changes
Nice one. Just one more thing and this should be good to merge.

2023-04-04 01:52 UTC, sidra2022 commented on apps/storybook/src/stories/datacom-link.stories.tsx
I have added stories to the stable folder. Thanks

2023-04-04 02:06 UTC, AngeCast approved these changes

2023-04-04 02:06 UTC, merged